In [65]:
import cx_Oracle
import pandas as pd
import os

from sklearn.model_selection import  train_test_split

In [6]:
import warnings
warnings.filterwarnings('ignore')

In [7]:
HighDividend=pd.read_excel('高股息.xlsx',header=1)

In [8]:
HighDividend

,投资经理,证券代码,证券名称,最新价,持仓,成本价,本币市值,市值/资产净值,盈亏率(%)
0,高股息,600036.STK.SH,招商银行,36.47,114125468,30.93,4.162156e+09,8.06%,0.179114
1,高股息,00939.STK.SHSC,建设银行,5.80,730119000,5.72,3.946500e+09,7.64%,0.013986
2,高股息,01088.STK.SHSC,中国神华,31.52,106676500,34.59,3.134429e+09,6.07%,-0.088754
3,高股息,00941.STK.SHSC,中国移动,71.02,42780000,70.89,2.832171e+09,5.48%,0.001834
4,高股息,00916.STK.SHSC,龙源电力,6.48,464190000,6.78,2.805021e+09,5.43%,-0.044248
5,高股息,00998.STK.SHSC,中信银行,4.90,610315000,4.67,2.791398e+09,5.41%,0.049251
6,高股息,01398.STK.SHSC,工商银行,4.51,616932000,4.66,2.593649e+09,5.02%,-0.032189
7,高股息,01109.STK.SHSC,华润置地,22.70,116099000,26.38,2.456555e+09,4.76%,-0.139500
8,高股息,600519.STK.SH,贵州茅台,1518.00,1538976,1467.35,2.336166e+09,4.52%,0.034518
9,高股息,00883.STK.SHSC,中国海洋石油,16.89,142059000,19.91,2.236665e+09,4.33%,-0.151683
10,高股息,02601.STK.SHSC,中国太保,24.04,94554600,18.14,2.118639e+09,4.1%,0.325248
11,高股息,01193.STK.SHSC,华润燃气,27.81,74493400,27.26,1.930693e+09,3.74%,0.020176
12,高股息,00386.STK.SHSC,中国石油化工股份,4.13,445862000,4.88,1.717905e+09,3.33%,-0.153689
13,高股息,000858.STK.SZ,五粮液,144.00,10784673,133.34,1.552993e+09,3.01%,0.079946
14,高股息,00836.STK.SHSC,华润电力,17.82,81422000,19.61,1.352677e+09,2.62%,-0.091280
15,高股息,600887.STK.SH,伊利股份,28.51,43366479,26.30,1.236378e+09,2.39%,0.084030
16,高股息,02328.STK.SHSC,中国财险,11.83,101539424,9.84,1.120216e+09,2.17%,0.202236
17,高股息,000568.STK.SZ,泸州老窖,136.14,8109311,136.72,1.104002e+09,2.14%,-0.004242
18,高股息,601666.STK.SH,平煤股份,9.96,89740923,10.49,8.938196e+08,1.73%,-0.050524
19,高股息,601288.STK.SH,农业银行,4.85,168183622,3.97,8.156906e+08,1.58%,0.221662
20,高股息,002415.STK.SZ,海康威视,29.80,24232829,31.24,7.221383e+08,1.4%,-0.046095
21,高股息,601398.STK.SH,工商银行,6.19,115125998,5.15,7.126299e+08,1.38%,0.201942
22,高股息,601939.STK.SH,建设银行,8.04,88016850,7.51,7.076555e+08,1.37%,0.070573
23,高股息,00168.STK.SHSC,青岛啤酒股份,47.78,15054000,50.05,6.704425e+08,1.3%,-0.045355
24,高股息,00371.STK.SHSC,北控水务集团,2.10,263430398,2.31,5.160174e+08,1%,-0.090909
25,高股息,600048.STK.SH,保利发展,10.03,46796100,9.90,4.693649e+08,0.91%,0.013131
26,高股息,01299.STK.SHSC,友邦保险,57.44,8734400,62.10,4.676803e+08,0.91%,-0.075040
27,高股息,600019.STK.SH,宝钢股份,6.62,70194067,6.00,4.646847e+08,0.9%,0.103333
28,高股息,00257.STK.SHSC,光大环境,3.47,113758000,3.29,3.678854e+08,0.71%,0.054711
29,高股息,601168.STK.SH,西部矿业,16.65,21553531,14.43,3.588663e+08,0.69%,0.153846
30,高股息,01816.STK.SHSC,中广核电力,2.56,148279000,2.80,3.548477e+08,0.69%,-0.085714
31,高股息,000933.STK.SZ,神火股份,15.88,19465503,16.79,3.091122e+08,0.6%,-0.054199
32,高股息,000932.STK.SZ,华菱钢铁,4.36,65420165,5.35,2.852319e+08,0.55%,-0.185047
33,高股息,601000.STK.SH,唐山港,4.25,67111176,3.90,2.852225e+08,0.55%,0.089744
34,高股息,000513.STK.SZ,丽珠集团,36.42,7794489,37.14,2.838753e+08,0.55%,-0.019386
35,高股息,01880.STK.SHSC,中国中免(港股),49.66,5820000,54.72,2.694159e+08,0.52%,-0.092471
36,高股息,300760.STK.SZ,迈瑞医疗,260.01,725791,275.52,1.887129e+08,0.37%,-0.056294
37,高股息,601298.STK.SH,青岛港,8.56,21666691,9.20,1.854669e+08,0.36%,-0.069565
38,高股息,06198.STK.SHSC,青岛港,5.41,28671000,5.79,1.443783e+08,0.28%,-0.065630
39,高股息,002271.STK.SZ,东方雨虹,13.49,10000400,16.50,1.349054e+08,0.26%,-0.182424
40,高股息,01313.STK.SHSC,华润建材科技,1.76,76166000,1.83,1.245653e+08,0.24%,-0.038251
41,高股息,300888.STK.SZ,稳健医疗,35.20,2942340,35.95,1.035704e+08,0.2%,-0.020862
42,高股息,600282.STK.SH,南钢股份,4.13,22775800,4.20,9.406405e+07,0.18%,-0.016667
43,高股息,601699.STK.SH,潞安环能,14.46,6492100,22.33,9.387577e+07,0.18%,-0.352441
44,高股息,00177.STK.SHSC,江苏宁沪高速公路,7.75,7792000,7.59,5.622928e+07,0.11%,0.021080
45,高股息,00956.STK.SHSC,新天绿色能源,3.37,2828000,3.38,8.884252e+06,0.02%,-0.002959
46,高股息,00914.STK.SHSC,海螺水泥(港股),20.28,200,16.12,3.779080e+03,0%,0.258065

In [9]:
HighDividend['证券代码']

0      600036.STK.SH
1     00939.STK.SHSC
2     01088.STK.SHSC
3     00941.STK.SHSC
4     00916.STK.SHSC
5     00998.STK.SHSC
6     01398.STK.SHSC
7     01109.STK.SHSC
8      600519.STK.SH
9     00883.STK.SHSC
10    02601.STK.SHSC
11    01193.STK.SHSC
12    00386.STK.SHSC
13     000858.STK.SZ
14    00836.STK.SHSC
15     600887.STK.SH
16    02328.STK.SHSC
17     000568.STK.SZ
18     601666.STK.SH
19     601288.STK.SH
20     002415.STK.SZ
21     601398.STK.SH
22     601939.STK.SH
23    00168.STK.SHSC
24    00371.STK.SHSC
25     600048.STK.SH
26    01299.STK.SHSC
27     600019.STK.SH
28    00257.STK.SHSC
29     601168.STK.SH
30    01816.STK.SHSC
31     000933.STK.SZ
32     000932.STK.SZ
33     601000.STK.SH
34     000513.STK.SZ
35    01880.STK.SHSC
36     300760.STK.SZ
37     601298.STK.SH
38    06198.STK.SHSC
39     002271.STK.SZ
40    01313.STK.SHSC
41     300888.STK.SZ
42     600282.STK.SH
43     601699.STK.SH
44    00177.STK.SHSC
45    00956.STK.SHSC
46    00914.STK.SHSC
Name: 证券代码, dtype: object

In [10]:
#只保留以‘.SH’和'.SZ'结尾的证券代码
mask=HighDividend['证券代码'].str.endswith('.SH') |  HighDividend['证券代码'].str.endswith('.SZ')
HighDividend_filter=HighDividend[mask]

In [11]:
#去除中间的‘.STK’
HighDividend_filter['证券代码']=HighDividend_filter['证券代码'].str.replace('.STK.','.')
HighDividend_filter.reset_index(drop=True,inplace=True)
HighDividend_filter

,投资经理,证券代码,证券名称,最新价,持仓,成本价,本币市值,市值/资产净值,盈亏率(%)
0,高股息,600036.SH,招商银行,36.47,114125468,30.93,4.162156e+09,8.06%,0.179114
1,高股息,600519.SH,贵州茅台,1518.00,1538976,1467.35,2.336166e+09,4.52%,0.034518
2,高股息,000858.SZ,五粮液,144.00,10784673,133.34,1.552993e+09,3.01%,0.079946
3,高股息,600887.SH,伊利股份,28.51,43366479,26.30,1.236378e+09,2.39%,0.084030
4,高股息,000568.SZ,泸州老窖,136.14,8109311,136.72,1.104002e+09,2.14%,-0.004242
5,高股息,601666.SH,平煤股份,9.96,89740923,10.49,8.938196e+08,1.73%,-0.050524
6,高股息,601288.SH,农业银行,4.85,168183622,3.97,8.156906e+08,1.58%,0.221662
7,高股息,002415.SZ,海康威视,29.80,24232829,31.24,7.221383e+08,1.4%,-0.046095
8,高股息,601398.SH,工商银行,6.19,115125998,5.15,7.126299e+08,1.38%,0.201942
9,高股息,601939.SH,建设银行,8.04,88016850,7.51,7.076555e+08,1.37%,0.070573
10,高股息,600048.SH,保利发展,10.03,46796100,9.90,4.693649e+08,0.91%,0.013131
11,高股息,600019.SH,宝钢股份,6.62,70194067,6.00,4.646847e+08,0.9%,0.103333
12,高股息,601168.SH,西部矿业,16.65,21553531,14.43,3.588663e+08,0.69%,0.153846
13,高股息,000933.SZ,神火股份,15.88,19465503,16.79,3.091122e+08,0.6%,-0.054199
14,高股息,000932.SZ,华菱钢铁,4.36,65420165,5.35,2.852319e+08,0.55%,-0.185047
15,高股息,601000.SH,唐山港,4.25,67111176,3.90,2.852225e+08,0.55%,0.089744
16,高股息,000513.SZ,丽珠集团,36.42,7794489,37.14,2.838753e+08,0.55%,-0.019386
17,高股息,300760.SZ,迈瑞医疗,260.01,725791,275.52,1.887129e+08,0.37%,-0.056294
18,高股息,601298.SH,青岛港,8.56,21666691,9.20,1.854669e+08,0.36%,-0.069565
19,高股息,002271.SZ,东方雨虹,13.49,10000400,16.50,1.349054e+08,0.26%,-0.182424
20,高股息,300888.SZ,稳健医疗,35.20,2942340,35.95,1.035704e+08,0.2%,-0.020862
21,高股息,600282.SH,南钢股份,4.13,22775800,4.20,9.406405e+07,0.18%,-0.016667
22,高股息,601699.SH,潞安环能,14.46,6492100,22.33,9.387577e+07,0.18%,-0.352441

In [12]:
HighDividend_trade=pd.read_excel('高股息交易流水.xlsx',header=0)

In [13]:
HighDividend_trade['证券代码']

0        601398.STK.SH
1       204001.REPO.SH
2        601939.STK.SH
3       204001.REPO.SH
4        600377.STK.SH
             ...
3792    00386.STK.SHSC
3793     601988.STK.SH
3794    01088.STK.SHSC
3795    204001.REPO.SH
3796     601211.STK.SH
Name: 证券代码, Length: 3797, dtype: object

In [14]:
#只保留以‘.SH’和'.SZ'结尾的证券代码
mask=HighDividend_trade['证券代码'].str.endswith('.SH') |  HighDividend_trade['证券代码'].str.endswith('.SZ')
HighDividend_trade_filter=HighDividend_trade[mask]

In [15]:
#去除中间的代码（‘STK’或者‘REPO'）
HighDividend_trade_filter['证券代码']=HighDividend_trade_filter['证券代码'].apply(lambda x:'.'.join([x.split('.')[0],x.split('.')[-1]]))
HighDividend_trade_filter

        产品代码      交易日期       证券代码      交易数量         交易金额
0     640043  20220919  601398.SH  20602500   89999725.0
1     640043  20221027  204001.SH         0          0.0
2     640043  20230202  601939.SH   8181380   45897541.8
3     640043  20230714  204001.SH   1180000  118000000.0
4     640043  20230705  600377.SH     73100     709070.0
...      ...       ...        ...       ...          ...
3790  649939  20240716  204001.SH   2200000  220000000.0
3791  640043  20240705  204001.SH         0          0.0
3793  640043  20220922  601988.SH   8130000   24999684.0
3795  640043  20200416  204001.SH         0          0.0
3796  640043  20200106  601211.SH     30000     566900.0

[2320 rows x 5 columns]

In [16]:
#去除交易数量和交易金额为0的行
trade_df=HighDividend_trade_filter[(HighDividend_trade_filter['交易数量']!=0)&(HighDividend_trade_filter['交易金额']!=0)]
trade_df

        产品代码      交易日期       证券代码      交易数量         交易金额
0     640043  20220919  601398.SH  20602500   89999725.0
2     640043  20230202  601939.SH   8181380   45897541.8
3     640043  20230714  204001.SH   1180000  118000000.0
4     640043  20230705  600377.SH     73100     709070.0
6     640043  20231013  601168.SH   5380300   69680853.0
...      ...       ...        ...       ...          ...
3784  649939  20240430  204001.SH  -1130000 -113000000.0
3789  640043  20240625  601288.SH  -5887300  -24999888.0
3790  649939  20240716  204001.SH   2200000  220000000.0
3793  640043  20220922  601988.SH   8130000   24999684.0
3796  640043  20200106  601211.SH     30000     566900.0

[2168 rows x 5 columns]

In [17]:
trade_df['证券代码'].unique()

array(['601398.SH', '601939.SH', '204001.SH', '600377.SH', '601168.SH',
       '600036.SH', '600019.SH', '600332.SH', '601699.SH', '601988.SH',
       '601928.SH', '000895.SZ', '000568.SZ', '000333.SZ', '600585.SH',
       '000858.SZ', '601000.SH', '601888.SH', '601328.SH', '600938.SH',
       '002027.SZ', '601601.SH', '600048.SH', '002532.SZ', '601088.SH',
       '600741.SH', '600941.SH', '600900.SH', '603128.SH', '601288.SH',
       '601298.SH', '600519.SH', '002557.SZ', '601369.SH', '603259.SH',
       '000513.SZ', '002737.SZ', '000932.SZ', '002415.SZ', '601666.SH',
       '688016.SH', '300244.SZ', '000708.SZ', '300888.SZ', '002601.SZ',
       '300759.SZ', '002271.SZ', '300033.SZ', '000028.SZ', '603883.SH',
       '300482.SZ', '600529.SH', '600383.SH', '000002.SZ', '603939.SH',
       '603127.SH', '002023.SZ', '300122.SZ', '600028.SH', '000933.SZ',
       '000651.SZ', '688202.SH', '600887.SH', '300009.SZ', '600282.SH',
       '600436.SH', '002332.SZ', '600547.SH', '601336.SH', '300679.SZ',
       '603456.SH', '601668.SH', '000983.SZ', '300558.SZ', '300298.SZ',
       '601377.SH', '688158.SH', '600329.SH', '600763.SH', '159949.SZ',
       '002422.SZ', '300433.SZ', '300451.SZ', '300725.SZ', '000661.SZ',
       '300146.SZ', '300760.SZ', '000739.SZ', '688002.SH', '002223.SZ',
       '600104.SH', '688029.SH', '601555.SH', '300463.SZ', '000538.SZ',
       '300636.SZ', '002317.SZ', '300630.SZ', '601211.SH', '600004.SH',
       '159948.SZ', '300731.SZ', '002821.SZ', '300003.SZ', '300347.SZ',
       '300529.SZ', '000034.SZ', '600276.SH', '002777.SZ', '300253.SZ',
       '600598.SH', '300601.SZ', '603987.SH', '601225.SH', '300603.SZ',
       '600188.SH', '688200.SH', '300088.SZ', '603496.SH'], dtype=object)

In [4]:
# #构造标签
# stock_code=pd.DataFrame(trade_df['证券代码'].unique(),columns=['证券代码'])
# stock_code['label']=0

NameError: name 'pd' is not defined

In [88]:
# mask1=stock_code['证券代码'].isin(HighDividend_filter['证券代码'])
# mask1

0       True
1       True
2      False
3      False
4       True
       ...
114    False
115    False
116    False
117    False
118    False
Name: 证券代码, Length: 119, dtype: bool

In [94]:
# #高股息持仓股票代码的lable设为1，其余为0
# stock_code.loc[mask1,'label']=1
# stock_code[mask1]

         证券代码  label
0   601398.SH      1
1   601939.SH      1
4   601168.SH      1
5   600036.SH      1
6   600019.SH      1
8   601699.SH      1
12  000568.SZ      1
15  000858.SZ      1
16  601000.SH      1
22  600048.SH      1
29  601288.SH      1
30  601298.SH      1
31  600519.SH      1
35  000513.SZ      1
37  000932.SZ      1
38  002415.SZ      1
39  601666.SH      1
43  300888.SZ      1
46  002271.SZ      1
59  000933.SZ      1
62  600887.SH      1
64  600282.SH      1
86  300760.SZ      1

In [95]:
# stock_code

          证券代码  label
0    601398.SH      1
1    601939.SH      1
2    204001.SH      0
3    600377.SH      0
4    601168.SH      1
..         ...    ...
114  300603.SZ      0
115  600188.SH      0
116  688200.SH      0
117  300088.SZ      0
118  603496.SH      0

[119 rows x 2 columns]

In [18]:
connection = cx_Oracle.connect('jylh', 'jylh', '10.6.60.114:1521/wind')
cursor = connection.cursor()
sql = "select * from ZQ_TABLE_FACTOR_BASE"
cursor.execute(sql)
columns = [col[0] for col in cursor.description]
results = cursor.fetchall()
X_df1 = pd.DataFrame(results, columns=columns)

In [97]:
X_df1.head(10)

,CJJG_DT,CJJG_CODE,CJJG_OP_YOY,CJJG_OP_TTM_YOY,CJJG_CP_YOY,CJJG_CP_TTM_YOY,CJJG_NP_YOY,CJJG_NP_TTM_YOY,CJJG_NPAT_YOY,CJJG_NPAT_TTM_YOY,...,CJJG_IC2EV,CJJG_EBIT2EV_12,CJJG_EBIT2EV_12_TTM,CJJG_EBITDA2EV_12,CJJG_EBITDA2EV_12_TTM,CJJG_NOPLAT2EV_12,CJJG_NOPLAT2EV_12_TTM,CJJG_SALES2EV_12,CJJG_SALES2EV_12_TTM,CJJG_IC2EV_12
0,2014-01-30 00:00:00,000001.SZ,0.196724,0.168806,1.843482,0.385955,0.198075,0.143897,0.198075,0.158345,...,NaN,0.051404,0.185071,0.044908,0.197002,0.043693,0.157311,0.132180,0.451667,1.026655
1,2014-01-30 00:00:00,000002.SZ,0.338531,0.246683,-0.495201,1.186220,0.329397,0.245914,0.183873,0.225762,...,0.797192,0.026568,0.190296,0.025838,0.191759,0.022583,0.161752,0.176472,0.964713,0.848755
2,2014-01-30 00:00:00,000004.SZ,0.424867,0.730541,-0.053802,0.293933,0.561909,0.435734,1.264476,0.618407,...,0.018419,0.003980,0.018721,0.001157,0.024199,0.003383,0.015913,0.018460,0.107726,0.019796
3,2014-01-30 00:00:00,000005.SZ,0.457453,1.104326,3.003978,13.168153,-1.412287,1.410064,-1.412287,1.410064,...,0.318605,-0.002768,0.010609,-0.003938,0.017311,-0.002353,0.009018,0.004655,0.039936,0.301575
4,2014-01-30 00:00:00,000006.SZ,0.193821,0.209714,0.156651,0.138701,0.141136,0.269371,0.155399,0.269641,...,0.863900,0.018058,0.124371,0.015862,0.127572,0.015349,0.105715,0.066502,0.398975,0.668959
5,2014-01-30 00:00:00,000007.SZ,-2.029642,-1.706082,2.287937,4.887350,5.854597,0.918013,7.587766,1.265808,...,0.149586,-0.000799,-0.001266,-0.002626,0.004216,-0.000679,-0.001076,0.011939,0.063092,0.153253
6,2014-01-30 00:00:00,000008.SZ,259.050399,13068.504644,53.643623,98.515685,194.717546,4326.896993,194.717546,4326.896993,...,0.180893,0.003600,0.030049,-0.005863,0.049723,0.003060,0.025541,0.032005,0.222186,0.174572
7,2014-01-30 00:00:00,000009.SZ,9.969335,1.158541,-0.156925,-0.080005,8.594471,1.640033,44.566166,3.220006,...,0.442340,0.027632,0.059103,0.023490,0.067988,0.023487,0.050238,0.057860,0.262868,0.466712
8,2014-01-30 00:00:00,000010.SZ,1.210288,4.031953,1.715224,0.702762,0.913070,6.336196,1.371333,20.557476,...,0.053301,-0.000048,0.003543,-0.000864,0.005131,-0.000041,0.003012,0.017737,0.080530,0.047733
9,2014-01-30 00:00:00,000025.SZ,29.013231,3.234653,1.481055,0.761461,23.949427,5.967925,11.710312,10.805090,...,0.186368,0.012454,0.020201,0.009675,0.026361,0.010586,0.017171,0.062373,0.209770,0.163286

In [99]:
#ASHAREFINANCIALINDICATOR(A股财务指标表）
connection = cx_Oracle.connect('wind', 'wind', '10.6.60.114:1521/wind')
cursor = connection.cursor()
sql = "select WIND_CODE,ANN_DT,REPORT_PERIOD,S_FA_ROE,S_FA_RETAINEDEARNINGS,S_FA_OCFTODEBT,S_FA_GROSSPROFITMARGIN from ASHAREFINANCIALINDICATOR"
cursor.execute(sql)
columns = [col[0] for col in cursor.description]
results = cursor.fetchall()
X_df2 = pd.DataFrame(results, columns=columns)

In [100]:
X_df2.head(10)

,WIND_CODE,ANN_DT,REPORT_PERIOD,S_FA_ROE,S_FA_RETAINEDEARNINGS,S_FA_OCFTODEBT,S_FA_GROSSPROFITMARGIN
0,A18114.SH,20100921,20091231,21.3054,4.166963e+08,0.0511,NaN
1,603323.SH,20100707,20091231,20.4745,8.442160e+08,0.0285,NaN
2,A16061.SH,20100427,20091231,4.5674,1.052963e+08,0.1051,NaN
3,A19222.SZ,20100428,20091231,5.0826,4.019933e+08,NaN,NaN
4,601375.SH,20100429,20091231,28.0171,1.092969e+09,0.5157,NaN
5,601916.SH,20090826,20090630,7.1215,9.290400e+08,0.0059,NaN
6,601916.SH,20100427,20091231,13.3353,6.703384e+08,0.0929,NaN
7,688629.SH,20110114,20091231,NaN,NaN,NaN,NaN
8,A22500.SH,20090720,20090630,6.7309,3.458128e+08,NaN,NaN
9,A22500.SH,20100423,20091231,10.7605,3.037130e+08,0.2489,NaN

In [101]:
#ASHAREEODPRICES(A股日行情）
connection = cx_Oracle.connect('wind', 'wind', '10.6.60.114:1521/wind')
cursor = connection.cursor()
sql = "select S_INFO_WINDCODE,TRADE_DT,S_DQ_AMOUNT,S_DQ_PCTCHANGE from ASHAREEODPRICES"
cursor.execute(sql)
columns = [col[0] for col in cursor.description]
results = cursor.fetchall()
X_df3 = pd.DataFrame(results, columns=columns)

In [102]:
X_df3.head(10)

  S_INFO_WINDCODE  TRADE_DT  S_DQ_AMOUNT  S_DQ_PCTCHANGE
0       000001.SZ  20090902  822035.7630          4.4211
1       000001.SZ  20090917  473194.3242          0.9868
2       000002.SZ  20090105  615404.4053          3.8760
3       000002.SZ  20090106  835047.7630          2.9851
4       000002.SZ  20090107  580781.8035         -0.5797
5       000002.SZ  20090109  432865.4316         -0.1449
6       000002.SZ  20090112  529016.5664         -1.1611
7       000002.SZ  20090113  588719.7460         -3.5242
8       000002.SZ  20090114  665967.8365          4.8706
9       000002.SZ  20090115  474415.2017         -0.5806

In [104]:
#ASHAREEARNINGEST(中国A股盈利预测明细）
connection = cx_Oracle.connect('wind', 'wind', '10.6.60.114:1521/wind')
cursor = connection.cursor()
sql = "select WIND_CODE,EST_DT,REPORTING_PERIOD,S_EST_DIVIDENDYIELD,EST_NET_PROFIT from ASHAREEARNINGEST"
cursor.execute(sql)
columns = [col[0] for col in cursor.description]
results = cursor.fetchall()
X_df4 = pd.DataFrame(results, columns=columns)

In [105]:
X_df4.head(10)

   WIND_CODE    EST_DT REPORTING_PERIOD  S_EST_DIVIDENDYIELD  EST_NET_PROFIT
0  601899.SH  20091029         20091231                  NaN        357100.0
1  601899.SH  20091029         20101231                  NaN        392500.0
2  601899.SH  20091029         20111231                  NaN        471300.0
3  601899.SH  20090323         20091231                  NaN        334500.0
4  601899.SH  20090323         20101231                  NaN        407100.0
5  601899.SH  20091210         20091231                  NaN        409709.0
6  601899.SH  20091210         20101231                  NaN        535362.0
7  601899.SH  20090323         20091231                  NaN        336014.0
8  601899.SH  20090323         20101231                  NaN        380674.0
9  601899.SH  20091201         20091231                  NaN        420600.0

In [106]:
#ASHAREEXRIGHTDIVIDENDRECORD(中国A股除权除息记录）
connection = cx_Oracle.connect('wind', 'wind', '10.6.60.114:1521/wind')
cursor = connection.cursor()
sql = "select S_INFO_WINDCODE,EX_DATE,CASH_DIVIDEND_RATIO from ASHAREEXRIGHTDIVIDENDRECORD"
cursor.execute(sql)
columns = [col[0] for col in cursor.description]
results = cursor.fetchall()
X_df5 = pd.DataFrame(results, columns=columns)

In [107]:
X_df5.head(10)

  S_INFO_WINDCODE   EX_DATE  CASH_DIVIDEND_RATIO
0       600242.SH  20090105                0.000
1       600259.SH  20090119                0.000
2       000668.SZ  20090123                0.000
3       000708.SZ  20090209                0.053
4       600892.SH  20090211                0.000
5       600435.SH  20090224                0.000
6       600892.SH  20090226                0.000
7       600892.SH  20090227                0.000
8       600800.SH  20090303                0.000
9       600800.SH  20090304                0.000

In [108]:
#ASHARECASHFLOW(A股现金流量表）
connection = cx_Oracle.connect('wind', 'wind', '10.6.60.114:1521/wind')
cursor = connection.cursor()
sql = "select WIND_CODE,ANN_DT,REPORT_PERIOD,NET_PROFIT,NET_CASH_FLOWS_OPER_ACT from ASHARECASHFLOW"
cursor.execute(sql)
columns = [col[0] for col in cursor.description]
results = cursor.fetchall()
X_df6 = pd.DataFrame(results, columns=columns)

In [109]:
X_df6.head(10)

   WIND_CODE    ANN_DT REPORT_PERIOD   NET_PROFIT  NET_CASH_FLOWS_OPER_ACT
0  600100.SH  20090812      20090630          NaN             1.210348e+08
1  000885.SZ  20091026      20090930          NaN             2.129064e+08
2  600497.SH  20090430      20090331          NaN             7.947860e+07
3  002473.SZ  20101021      20090930          NaN             1.291145e+05
4  601328.SH  20091029      20090930          NaN             8.573400e+10
5  600287.SH  20090829      20090630 -55660033.26             2.590587e+06
6  600853.SH  20110401      20091231  11205143.72            -1.520442e+07
7  600232.SH  20110419      20091231  23269097.22             2.786278e+07
8  600526.SH  20110426      20091231   6014763.88            -1.507714e+07
9  600120.SH  20090430      20090331          NaN             3.802702e+07

In [110]:
#ASHAREEODDERIVATIVEINDICATOR(中国A股日行情估值指标）
connection = cx_Oracle.connect('wind', 'wind', '10.6.60.114:1521/wind')
cursor = connection.cursor()
sql = "select S_INFO_WINDCODE,TRADE_DT,S_DQ_TURN,S_VAL_PB_NEW,S_VAL_PE_TTM,S_PRICE_DIV_DPS from ASHAREEODDERIVATIVEINDICATOR"
cursor.execute(sql)
columns = [col[0] for col in cursor.description]
results = cursor.fetchall()
X_df7 = pd.DataFrame(results, columns=columns)

In [111]:
X_df7.head(10)

,S_INFO_WINDCODE,TRADE_DT,S_DQ_TURN,S_VAL_PB_NEW,S_VAL_PE_TTM,S_PRICE_DIV_DPS
0,300665.SZ,20210207,NaN,2.3485,43.4315,NaN
1,300599.SZ,20210207,NaN,1.9766,15.4883,NaN
2,688313.SH,20210207,NaN,7.9693,232.7788,NaN
3,300580.SZ,20210207,NaN,2.1104,19.4710,NaN
4,000655.SZ,20210207,NaN,1.3657,17.8627,NaN
5,603683.SH,20210207,NaN,1.9291,45.2834,NaN
6,688596.SH,20210207,NaN,2.3328,32.6188,NaN
7,300753.SZ,20210207,NaN,3.6466,29.9839,NaN
8,300619.SZ,20210207,NaN,2.6119,213.1975,NaN
9,603329.SH,20210207,NaN,2.4263,NaN,NaN

In [112]:
#ASHAREINCOME(A股利润表）
connection = cx_Oracle.connect('wind', 'wind', '10.6.60.114:1521/wind')
cursor = connection.cursor()
sql = "select WIND_CODE,ANN_DT,REPORT_PERIOD,OPER_REV,LESS_OPER_COST,OPER_PROFIT,NET_PROFIT_INCL_MIN_INT_INC from ASHAREINCOME"
cursor.execute(sql)
columns = [col[0] for col in cursor.description]
results = cursor.fetchall()
X_df8 = pd.DataFrame(results, columns=columns)

In [113]:
X_df8.head(10)

,WIND_CODE,ANN_DT,REPORT_PERIOD,OPER_REV,LESS_OPER_COST,OPER_PROFIT,NET_PROFIT_INCL_MIN_INT_INC
0,300265.SZ,20110826,20091231,3.865368e+08,2.885852e+08,24199182.30,21748477.42
1,300265.SZ,20110826,20091231,6.276537e+07,2.967500e+07,15674216.75,13335806.53
2,300288.SZ,20120106,20091231,4.342126e+07,1.040929e+07,15580583.43,12858725.52
3,300355.SZ,20120831,20091231,2.456534e+08,1.910851e+08,29575470.12,32877844.11
4,300355.SZ,20120831,20091231,2.456534e+08,1.910851e+08,29575470.12,32877844.11
5,002033.SZ,20090422,20090331,3.022523e+07,5.801805e+06,11583511.94,9652626.93
6,002033.SZ,20090422,20090331,3.022523e+07,5.801805e+06,11583511.94,9652626.93
7,002033.SZ,20100424,20090331,3.022523e+07,5.801805e+06,11583511.94,9652626.93
8,002033.SZ,20100424,20090331,3.022523e+07,5.801805e+06,11583511.94,9652626.93
9,002033.SZ,20090422,20090331,1.468646e+07,2.130219e+06,13052036.34,12445982.50

In [114]:
#ASHAREBALANCESHEET(A股资产负债表）
connection = cx_Oracle.connect('wind', 'wind', '10.6.60.114:1521/wind')
cursor = connection.cursor()
sql = "select WIND_CODE,ANN_DT,REPORT_PERIOD,TOT_ASSETS,TOT_SHR from ASHAREBALANCESHEET"
cursor.execute(sql)
columns = [col[0] for col in cursor.description]
results = cursor.fetchall()
X_df9 = pd.DataFrame(results, columns=columns)

In [115]:
X_df9.head(10)

   WIND_CODE    ANN_DT REPORT_PERIOD    TOT_ASSETS      TOT_SHR
0  601528.SH  20110607      20091231  4.137485e+10  600000000.0
1  002033.SZ  20091021      20090930  9.709780e+08   99323048.0
2  002033.SZ  20100208      20091231  1.016595e+09   99323048.0
3  002033.SZ  20110310      20091231  9.082434e+08   99323048.0
4  300001.SZ  20091026      20090930  1.096010e+09  133600000.0
5  300001.SZ  20110301      20091231  1.082560e+09  133600000.0
6  300001.SZ  20110301      20091231  1.082560e+09  133600000.0
7  300020.SZ  20091026      20090930  5.130791e+08   60000000.0
8  601022.SH  20100129      20090930  1.256327e+08          NaN
9  601022.SH  20100722      20091231  1.404000e+08          NaN

In [116]:
#ASHARESALESSEGMENT(中国A股主营业务构成）
connection = cx_Oracle.connect('wind', 'wind', '10.6.60.114:1521/wind')
cursor = connection.cursor()
sql = "select S_INFO_WINDCODE,REPORT_PERIOD,S_SEGMENT_SALES from ASHARESALESSEGMENT"
cursor.execute(sql)
columns = [col[0] for col in cursor.description]
results = cursor.fetchall()
X_df10 = pd.DataFrame(results, columns=columns)

In [117]:
X_df10.head(10)

  S_INFO_WINDCODE REPORT_PERIOD  S_SEGMENT_SALES
0       A21744.BJ      20141231     3.803186e+07
1       A21744.BJ      20141231     1.263184e+08
2       A21744.BJ      20141231     1.528462e+07
3       A21744.BJ      20141231     8.828651e+07
4       A21744.BJ      20141231     1.611957e+06
5       A21744.BJ      20141231     6.009829e+05
6       A21744.BJ      20141231     5.196848e+06
7       A21744.BJ      20141231     2.218694e+07
8       A21744.BJ      20141231     1.263184e+08
9       A21744.BJ      20141231     1.225547e+05

In [118]:
#ASHARETTMHIS(A股TTM指标历史数据）
connection = cx_Oracle.connect('wind', 'wind', '10.6.60.114:1521/wind')
cursor = connection.cursor()
sql = "select S_INFO_WINDCODE,ANN_DT,REPORT_PERIOD,NET_CASH_FLOWS_OPER_ACT_TTM,S_FA_OP_TTM,NET_PROFIT_PARENT_COMP_TTM from ASHARETTMHIS"
cursor.execute(sql)
columns = [col[0] for col in cursor.description]
results = cursor.fetchall()
X_df11 = pd.DataFrame(results, columns=columns)

In [119]:
X_df11.head(10)

,S_INFO_WINDCODE,ANN_DT,REPORT_PERIOD,NET_CASH_FLOWS_OPER_ACT_TTM,S_FA_OP_TTM,NET_PROFIT_PARENT_COMP_TTM
0,603003.SH,20120727,20091231,3.656925e+07,8.004557e+07,6.584283e+07
1,601118.SH,20100210,20090630,4.513077e+08,3.123433e+08,3.372755e+08
2,601118.SH,20101216,20091231,4.141887e+08,2.474167e+08,2.857452e+08
3,603111.SH,20120713,20091231,4.464096e+07,6.350312e+07,6.296616e+07
4,603099.SH,20120713,20091231,9.046440e+07,6.110380e+07,5.563320e+07
5,300388.SZ,20130125,20091231,1.563759e+08,2.994565e+07,2.820565e+07
6,002091.SZ,20090424,20090331,1.721258e+08,1.624406e+08,1.323051e+08
7,002091.SZ,20090731,20090630,2.543351e+08,1.719400e+08,1.340428e+08
8,002091.SZ,20091024,20090930,2.949739e+08,1.837397e+08,1.436599e+08
9,002091.SZ,20100318,20091231,1.032504e+08,1.975105e+08,1.475298e+08

In [121]:
#TQ_SK_FININDIC(股票交易财务衍生表）
connection = cx_Oracle.connect('finchina', 'finchina', '10.6.60.118:1521/orcl')
cursor = connection.cursor()
sql = "select SYMBOL,TRADEDATE,LTDATE,PB,PETTM from TQ_SK_FININDIC"
cursor.execute(sql)
columns = [col[0] for col in cursor.description]
results = cursor.fetchall()
X_df12 = pd.DataFrame(results, columns=columns)

In [122]:
X_df12.head(10)

   SYMBOL TRADEDATE    LTDATE       PB      PETTM
0  900917  19931208  19000101      NaN        NaN
1  900918  19931210  19000101      NaN    59.5643
2  900924  19940118  19000101      NaN        NaN
3  900931  19941110  19000101   1.7913    10.4519
4  000502  19921123  19000101   9.1513    41.9422
5  200030  19930929  19000101   3.2502    16.7359
6  200028  19930809  19000101   3.0876    13.1565
7  200019  19921012  19000101   7.6478    37.1434
8  600018  20061025  20060925  41.9734  1764.3292
9  600018  20061024  20060925  41.9734  1764.3292

In [19]:
X_df1.head()

,CJJG_DT,CJJG_CODE,CJJG_OP_YOY,CJJG_OP_TTM_YOY,CJJG_CP_YOY,CJJG_CP_TTM_YOY,CJJG_NP_YOY,CJJG_NP_TTM_YOY,CJJG_NPAT_YOY,CJJG_NPAT_TTM_YOY,...,CJJG_IC2EV,CJJG_EBIT2EV_12,CJJG_EBIT2EV_12_TTM,CJJG_EBITDA2EV_12,CJJG_EBITDA2EV_12_TTM,CJJG_NOPLAT2EV_12,CJJG_NOPLAT2EV_12_TTM,CJJG_SALES2EV_12,CJJG_SALES2EV_12_TTM,CJJG_IC2EV_12
0,2014-01-30 00:00:00,000001.SZ,0.196724,0.168806,1.843482,0.385955,0.198075,0.143897,0.198075,0.158345,...,NaN,0.051404,0.185071,0.044908,0.197002,0.043693,0.157311,0.132180,0.451667,1.026655
1,2014-01-30 00:00:00,000002.SZ,0.338531,0.246683,-0.495201,1.186220,0.329397,0.245914,0.183873,0.225762,...,0.797192,0.026568,0.190296,0.025838,0.191759,0.022583,0.161752,0.176472,0.964713,0.848755
2,2014-01-30 00:00:00,000004.SZ,0.424867,0.730541,-0.053802,0.293933,0.561909,0.435734,1.264476,0.618407,...,0.018419,0.003980,0.018721,0.001157,0.024199,0.003383,0.015913,0.018460,0.107726,0.019796
3,2014-01-30 00:00:00,000005.SZ,0.457453,1.104326,3.003978,13.168153,-1.412287,1.410064,-1.412287,1.410064,...,0.318605,-0.002768,0.010609,-0.003938,0.017311,-0.002353,0.009018,0.004655,0.039936,0.301575
4,2014-01-30 00:00:00,000006.SZ,0.193821,0.209714,0.156651,0.138701,0.141136,0.269371,0.155399,0.269641,...,0.863900,0.018058,0.124371,0.015862,0.127572,0.015349,0.105715,0.066502,0.398975,0.668959

In [20]:
X_df1.dropna(inplace=True)
X_df1.shape

(414765, 105)

In [21]:
X_df1['CJJG_CODE'].unique()

array(['000002.SZ', '000004.SZ', '000005.SZ', ..., '301291.SZ',
       '301293.SZ', '301295.SZ'], dtype=object)

In [22]:
X_df1['CJJG_DT'].unique()

array(['2014-01-30 00:00:00', '2014-02-28 00:00:00',
       '2014-03-31 00:00:00', '2014-04-30 00:00:00',
       '2014-05-30 00:00:00', '2014-06-30 00:00:00',
       '2014-07-31 00:00:00', '2014-08-29 00:00:00',
       '2014-09-30 00:00:00', '2014-10-31 00:00:00',
       '2014-11-28 00:00:00', '2014-12-31 00:00:00',
       '2015-01-30 00:00:00', '2015-02-27 00:00:00',
       '2015-03-31 00:00:00', '2015-04-30 00:00:00',
       '2015-05-29 00:00:00', '2015-06-30 00:00:00',
       '2015-07-31 00:00:00', '2015-08-31 00:00:00',
       '2015-09-30 00:00:00', '2015-10-30 00:00:00',
       '2015-11-30 00:00:00', '2015-12-31 00:00:00',
       '2016-01-29 00:00:00', '2016-02-29 00:00:00',
       '2016-03-31 00:00:00', '2016-04-29 00:00:00',
       '2016-05-31 00:00:00', '2016-06-30 00:00:00',
       '2016-09-30 00:00:00', '2016-08-31 00:00:00',
       '2016-07-29 00:00:00', '2016-12-30 00:00:00',
       '2016-11-30 00:00:00', '2016-10-31 00:00:00',
       '2017-04-28 00:00:00', '2017-03-31 00:00:00',
       '2017-02-28 00:00:00', '2017-01-26 00:00:00',
       '2017-07-31 00:00:00', '2017-06-30 00:00:00',
       '2017-05-31 00:00:00', '2017-10-31 00:00:00',
       '2017-08-31 00:00:00', '2017-09-29 00:00:00',
       '2018-01-31 00:00:00', '2017-12-29 00:00:00',
       '2017-11-30 00:00:00', '2018-03-30 00:00:00',
       '2018-04-27 00:00:00', '2018-02-28 00:00:00',
       '2018-06-29 00:00:00', '2018-05-31 00:00:00',
       '2018-09-28 00:00:00', '2018-08-31 00:00:00',
       '2018-07-31 00:00:00', '2018-12-28 00:00:00',
       '2018-11-30 00:00:00', '2018-10-31 00:00:00',
       '2019-02-28 00:00:00', '2019-01-31 00:00:00',
       '2019-05-31 00:00:00', '2019-04-30 00:00:00',
       '2019-03-29 00:00:00', '2019-08-30 00:00:00',
       '2019-07-31 00:00:00', '2019-06-28 00:00:00',
       '2019-10-31 00:00:00', '2019-09-30 00:00:00',
       '2020-01-23 00:00:00', '2019-12-31 00:00:00',
       '2019-11-29 00:00:00', '2020-03-31 00:00:00',
       '2020-02-28 00:00:00', '2020-06-30 00:00:00',
       '2020-05-29 00:00:00', '2020-04-30 00:00:00',
       '2020-08-31 00:00:00', '2020-07-31 00:00:00',
       '2020-11-30 00:00:00', '2020-10-30 00:00:00',
       '2020-09-30 00:00:00', '2021-01-29 00:00:00',
       '2020-12-31 00:00:00', '2021-04-30 00:00:00',
       '2021-03-31 00:00:00', '2021-02-26 00:00:00',
       '2021-06-30 00:00:00', '2021-05-31 00:00:00',
       '2021-08-31 00:00:00', '2021-07-30 00:00:00',
       '2021-10-29 00:00:00', '2021-09-30 00:00:00',
       '2021-12-31 00:00:00', '2021-11-30 00:00:00',
       '2022-02-28 00:00:00', '2022-03-31 00:00:00',
       '2022-01-28 00:00:00', '2022-05-31 00:00:00',
       '2022-04-29 00:00:00', '2022-07-29 00:00:00',
       '2022-06-30 00:00:00', '2022-09-30 00:00:00',
       '2022-08-31 00:00:00', '2022-11-30 00:00:00',
       '2022-10-31 00:00:00', '2023-01-31 00:00:00',
       '2022-12-30 00:00:00', '2023-02-28 00:00:00',
       '2023-03-31 00:00:00', '2023-04-28 00:00:00',
       '2023-06-30 00:00:00', '2023-05-31 00:00:00',
       '2023-08-31 00:00:00', '2023-07-31 00:00:00',
       '2023-10-31 00:00:00', '2023-09-28 00:00:00',
       '2023-12-29 00:00:00', '2023-11-30 00:00:00',
       '2024-02-29 00:00:00', '2024-01-31 00:00:00',
       '2024-03-29 00:00:00', '2024-04-30 00:00:00',
       '2024-05-31 00:00:00', '2024-07-31 00:00:00',
       '2024-06-28 00:00:00', '2024-08-30 00:00:00'], dtype=object)

In [23]:
X_df1['CJJG_DT']=pd.to_datetime(X_df1['CJJG_DT'])
feature_columns=[col for col in X_df1.columns if col not in ['CJJG_DT','CJJG_CODE']]

In [24]:
#计算每个股票在所有时间点的特征平均值
X_df1_grouped=X_df1.groupby(['CJJG_CODE'])[feature_columns].mean()
X_df1_grouped.head()

,CJJG_OP_YOY,CJJG_OP_TTM_YOY,CJJG_CP_YOY,CJJG_CP_TTM_YOY,CJJG_NP_YOY,CJJG_NP_TTM_YOY,CJJG_NPAT_YOY,CJJG_NPAT_TTM_YOY,CJJG_DNP_YOY,CJJG_DNP_TTM_YOY,...,CJJG_IC2EV,CJJG_EBIT2EV_12,CJJG_EBIT2EV_12_TTM,CJJG_EBITDA2EV_12,CJJG_EBITDA2EV_12_TTM,CJJG_NOPLAT2EV_12,CJJG_NOPLAT2EV_12_TTM,CJJG_SALES2EV_12,CJJG_SALES2EV_12_TTM,CJJG_IC2EV_12
CJJG_CODE,,,,,,,,,,,,,,,,,,,,,
000002.SZ,0.111317,0.073870,0.342617,-1.189390,0.095144,0.070082,0.031613,0.041745,-0.064621,0.023483,...,0.971488,0.023648,0.149674,0.022286,0.157878,0.020101,0.127223,0.172456,0.922466,0.745758
000004.SZ,6.152907,0.345431,47.655493,0.765968,0.190833,1.145606,-1.149194,2.027983,3.888019,-2.969142,...,0.167677,-0.001108,-0.074197,-0.001680,-0.070911,-0.000941,-0.063067,0.023170,0.101837,0.171328
000005.SZ,-8.891665,-2.657617,7.125895,2.911289,-1.932067,-0.298750,-0.069003,-0.304216,-0.846475,-1.907685,...,0.569388,0.001215,-0.006384,0.000619,-0.002435,0.001033,-0.005427,0.024246,0.109308,0.478418
000006.SZ,0.434858,0.053698,0.285459,-0.317683,0.333092,-0.014637,0.387440,-0.007193,1.227145,-0.017946,...,0.902038,0.019201,0.103444,0.018508,0.107915,0.016321,0.087927,0.059056,0.348522,0.917025
000007.SZ,1.191193,-6.601117,0.146228,0.049986,0.231864,-2.610588,1.382981,-3.147577,0.240186,-0.768691,...,0.057553,0.000352,0.000099,-0.000050,0.002665,0.000299,0.000084,0.012608,0.049300,0.055434

In [25]:
X_df1_grouped.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4886 entries, 000002.SZ to 689009.SH
Columns: 103 entries, CJJG_OP_YOY to CJJG_IC2EV_12
dtypes: float64(103)
memory usage: 3.9+ MB

In [27]:
X_df1_grouped.index

Index(['000002.SZ', '000004.SZ', '000005.SZ', '000006.SZ', '000007.SZ',
       '000008.SZ', '000009.SZ', '000010.SZ', '000011.SZ', '000012.SZ',
       ...
       '688787.SH', '688788.SH', '688789.SH', '688793.SH', '688798.SH',
       '688799.SH', '688800.SH', '688819.SH', '688981.SH', '689009.SH'],
      dtype='object', name='CJJG_CODE', length=4886)

array(['601398.SH', '601939.SH', '204001.SH', '600377.SH', '601168.SH',
       '600036.SH', '600019.SH', '600332.SH', '601699.SH', '601988.SH',
       '601928.SH', '000895.SZ', '000568.SZ', '000333.SZ', '600585.SH',
       '000858.SZ', '601000.SH', '601888.SH', '601328.SH', '600938.SH',
       '002027.SZ', '601601.SH', '600048.SH', '002532.SZ', '601088.SH',
       '600741.SH', '600941.SH', '600900.SH', '603128.SH', '601288.SH',
       '601298.SH', '600519.SH', '002557.SZ', '601369.SH', '603259.SH',
       '000513.SZ', '002737.SZ', '000932.SZ', '002415.SZ', '601666.SH',
       '688016.SH', '300244.SZ', '000708.SZ', '300888.SZ', '002601.SZ',
       '300759.SZ', '002271.SZ', '300033.SZ', '000028.SZ', '603883.SH',
       '300482.SZ', '600529.SH', '600383.SH', '000002.SZ', '603939.SH',
       '603127.SH', '002023.SZ', '300122.SZ', '600028.SH', '000933.SZ',
       '000651.SZ', '688202.SH', '600887.SH', '300009.SZ', '600282.SH',
       '600436.SH', '002332.SZ', '600547.SH', '601336.SH', '300679.SZ',
       '603456.SH', '601668.SH', '000983.SZ', '300558.SZ', '300298.SZ',
       '601377.SH', '688158.SH', '600329.SH', '600763.SH', '159949.SZ',
       '002422.SZ', '300433.SZ', '300451.SZ', '300725.SZ', '000661.SZ',
       '300146.SZ', '300760.SZ', '000739.SZ', '688002.SH', '002223.SZ',
       '600104.SH', '688029.SH', '601555.SH', '300463.SZ', '000538.SZ',
       '300636.SZ', '002317.SZ', '300630.SZ', '601211.SH', '600004.SH',
       '159948.SZ', '300731.SZ', '002821.SZ', '300003.SZ', '300347.SZ',
       '300529.SZ', '000034.SZ', '600276.SH', '002777.SZ', '300253.SZ',
       '600598.SH', '300601.SZ', '603987.SH', '601225.SH', '300603.SZ',
       '600188.SH', '688200.SH', '300088.SZ', '603496.SH'], dtype=object)

In [56]:
#构造标签
stock_code=pd.DataFrame({'证券代码':X_df1_grouped.index})
stock_code['label']=0
stock_code

           证券代码  label
0     000002.SZ      0
1     000004.SZ      0
2     000005.SZ      0
3     000006.SZ      0
4     000007.SZ      0
...         ...    ...
4881  688799.SH      0
4882  688800.SH      0
4883  688819.SH      0
4884  688981.SH      0
4885  689009.SH      0

[4886 rows x 2 columns]

In [51]:
stock_set=set(stock_code['证券代码'])
trade_set=set(trade_df['证券代码'])
inser=stock_set&trade_set
len(inser)

105

In [59]:
mask2=stock_code['证券代码'].isin(trade_df['证券代码'])
mask2

0        True
1       False
2       False
3       False
4       False
        ...
4881    False
4882    False
4883    False
4884    False
4885    False
Name: 证券代码, Length: 4886, dtype: bool

In [60]:
#高股息持仓股票代码的lable设为1，其余为0
stock_code.loc[mask2,'label']=1
stock_code

           证券代码  label
0     000002.SZ      1
1     000004.SZ      0
2     000005.SZ      0
3     000006.SZ      0
4     000007.SZ      0
...         ...    ...
4881  688799.SH      0
4882  688800.SH      0
4883  688819.SH      0
4884  688981.SH      0
4885  689009.SH      0

[4886 rows x 2 columns]

In [61]:
X_df1_grouped.head()

,CJJG_OP_YOY,CJJG_OP_TTM_YOY,CJJG_CP_YOY,CJJG_CP_TTM_YOY,CJJG_NP_YOY,CJJG_NP_TTM_YOY,CJJG_NPAT_YOY,CJJG_NPAT_TTM_YOY,CJJG_DNP_YOY,CJJG_DNP_TTM_YOY,...,CJJG_IC2EV,CJJG_EBIT2EV_12,CJJG_EBIT2EV_12_TTM,CJJG_EBITDA2EV_12,CJJG_EBITDA2EV_12_TTM,CJJG_NOPLAT2EV_12,CJJG_NOPLAT2EV_12_TTM,CJJG_SALES2EV_12,CJJG_SALES2EV_12_TTM,CJJG_IC2EV_12
CJJG_CODE,,,,,,,,,,,,,,,,,,,,,
000002.SZ,0.111317,0.073870,0.342617,-1.189390,0.095144,0.070082,0.031613,0.041745,-0.064621,0.023483,...,0.971488,0.023648,0.149674,0.022286,0.157878,0.020101,0.127223,0.172456,0.922466,0.745758
000004.SZ,6.152907,0.345431,47.655493,0.765968,0.190833,1.145606,-1.149194,2.027983,3.888019,-2.969142,...,0.167677,-0.001108,-0.074197,-0.001680,-0.070911,-0.000941,-0.063067,0.023170,0.101837,0.171328
000005.SZ,-8.891665,-2.657617,7.125895,2.911289,-1.932067,-0.298750,-0.069003,-0.304216,-0.846475,-1.907685,...,0.569388,0.001215,-0.006384,0.000619,-0.002435,0.001033,-0.005427,0.024246,0.109308,0.478418
000006.SZ,0.434858,0.053698,0.285459,-0.317683,0.333092,-0.014637,0.387440,-0.007193,1.227145,-0.017946,...,0.902038,0.019201,0.103444,0.018508,0.107915,0.016321,0.087927,0.059056,0.348522,0.917025
000007.SZ,1.191193,-6.601117,0.146228,0.049986,0.231864,-2.610588,1.382981,-3.147577,0.240186,-0.768691,...,0.057553,0.000352,0.000099,-0.000050,0.002665,0.000299,0.000084,0.012608,0.049300,0.055434

In [63]:
X_train,X_test,y_train,y_test=train_test_split()